config/routes.rb
Language::Application.routes.draw do
  resources :langs

  resources :levels

  root 'langs#index'

end

app/models/lang.rb
class Lang < ActiveRecord::Base
  belongs_to :level
end

app/models/level.rb
class Level < ActiveRecord::Base
	has_many :langs, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/langs_controller.rb
class LangsController < ApplicationController
  before_action :set_lang, only: [:show, :edit, :update, :destroy]

  # GET /langs
  # GET /langs.json
  def index
    @langs = Lang.all
  end

  # GET /langs/1
  # GET /langs/1.json
  def show
  end

  # GET /langs/new
  def new
    @lang = Lang.new
  end

  # GET /langs/1/edit
  def edit
  end

  # POST /langs
  # POST /langs.json
  def create
    @lang = Lang.new(lang_params)

    respond_to do |format|
      if @lang.save
        format.html { redirect_to @lang, notice: 'Lang was successfully created.' }
        format.json { render action: 'show', status: :created, location: @lang }
      else
        format.html { render action: 'new' }
        format.json { render json: @lang.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /langs/1
  # PATCH/PUT /langs/1.json
  def update
    respond_to do |format|
      if @lang.update(lang_params)
        format.html { redirect_to @lang, notice: 'Lang was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lang.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /langs/1
  # DELETE /langs/1.json
  def destroy
    @lang.destroy
    respond_to do |format|
      format.html { redirect_to langs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lang
      @lang = Lang.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lang_params
      params.require(:lang).permit(:name, :level_id)
    end
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_action :set_level, only: [:show, :edit, :update, :destroy]

  # GET /levels
  # GET /levels.json
  def index
    @levels = Level.all
  end

  # GET /levels/1
  # GET /levels/1.json
  def show
  end

  # GET /levels/new
  def new
    @level = Level.new
  end

  # GET /levels/1/edit
  def edit
  end

  # POST /levels
  # POST /levels.json
  def create
    @level = Level.new(level_params)

    respond_to do |format|
      if @level.save
        format.html { redirect_to @level, notice: 'Level was successfully created.' }
        format.json { render action: 'show', status: :created, location: @level }
      else
        format.html { render action: 'new' }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /levels/1
  # PATCH/PUT /levels/1.json
  def update
    respond_to do |format|
      if @level.update(level_params)
        format.html { redirect_to @level, notice: 'Level was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /levels/1
  # DELETE /levels/1.json
  def destroy
    @level.destroy
    respond_to do |format|
      format.html { redirect_to levels_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_level
      @level = Level.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def level_params
      params.require(:level).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/langs_helper.rb
module LangsHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/views/langs/_form.html.erb
<%= form_for(@lang) do |f| %>
  <% if @lang.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lang.errors.count, "error") %> prohibited this lang from being saved:</h2>

      <ul>
      <% @lang.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :level_id %><br>
    <%= f.collection_select :level_id, Level.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/langs/edit.html.erb
<h1>Editing lang</h1>

<%= render 'form' %>

<%= link_to 'Show', @lang %> |
<%= link_to 'Back', langs_path %>

app/views/langs/index.html.erb
<h1>Listing langs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Level</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @langs.each do |lang| %>
      <tr>
        <td><%= lang.name %></td>
        <td><%= lang.level.name %></td>
        <td><%= link_to 'Show', lang %></td>
        <td><%= link_to 'Edit', edit_lang_path(lang) %></td>
        <td><%= link_to 'Destroy', lang, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lang', new_lang_path %>

app/views/langs/new.html.erb
<h1>New lang</h1>

<%= render 'form' %>

<%= link_to 'Back', langs_path %>

app/views/langs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lang.name %>
</p>

<p>
  <strong>Level:</strong>
  <%= @lang.level.name %>
</p>

<%= link_to 'Edit', edit_lang_path(@lang) %> |
<%= link_to 'Back', langs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Language</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to 'Levels' ,levels_path %>
<%= link_to 'Langaues',  langs_path(@lang) %>
<%= yield %>

</body>
</html>

app/views/levels/_form.html.erb
<%= form_for(@level) do |f| %>
  <% if @level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@level.errors.count, "error") %> prohibited this level from being saved:</h2>

      <ul>
      <% @level.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/levels/edit.html.erb
<h1>Editing level</h1>

<%= render 'form' %>

<%= link_to 'Show', @level %> |
<%= link_to 'Back', levels_path %>

app/views/levels/index.html.erb
<h1>Listing levels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @levels.each do |level| %>
      <tr>
        <td><%= level.name %></td>
        <td><%= link_to 'Show', level %></td>
        <td><%= link_to 'Edit', edit_level_path(level) %></td>
        <td><%= link_to 'Destroy', level, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Level', new_level_path %>

app/views/levels/new.html.erb
<h1>New level</h1>

<%= render 'form' %>

<%= link_to 'Back', levels_path %>

app/views/levels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @level.name %>
</p>

<%= link_to 'Edit', edit_level_path(@level) %> |
<%= link_to 'Back', levels_path %>